annotation_allowed_biotypes:
- protein_coding
- non_coding
- 3prime_overlapping_ncRNA
- antisense
- lincRNA
- retained_intron
- sense_intronic
- sense_overlapping
- macro_lncRNA
- bidirectional_promoter_lncRNA
- miRNA
annotation_min_mapq: 10
bsseq_local_correct: false
cgi_annotation_file: ../../../../../../work/sdz852/wgbs/wg-blimp/fastq/cgi-GRCm39.csv.gz
computing_threads: 8
dmr_tools:
- bsseq
- metilene
gene_annotation_file: ../../../../../../work/sdz852/wgbs/wg-blimp/fastq/gencode.vM27.annotation.gtf.gz
group1:
- ES_L001_R1
- ES_L001_R2
- ES_L001_R3
group2:
- TF_L001_R1
- TF_L001_R2
- TF_L001_R3
io_threads: 8
methylation_rate_on_chromosomes: []
methylseekr_cgi_genome: mm39
methylseekr_fdr_cutoff: 5
methylseekr_methylation_cutoff: 0.5
methylseekr_pmd_chromosome: chr19
min_cov: 5
min_cpg: 5
min_diff: 0.3
output_dir: /work/sdz852/wgbs/wg-blimp/results2
promoter_tss_distances:
- -1000
- 1000
qualimap_memory_gb: 32
rawdir: ../../../../../../work/sdz852/wgbs/wg-blimp/fastq
rawsuffixregex:
  first: (_001)\.(fastq|fq)(\.gz)?
  second: (_002)\.(fastq|fq)(\.gz)?
ref: /work/sdz852/wgbs/wg-blimp/fastq/GRCm39.genome.fa
repeat_masker_annotation_file: ../../../../../../work/sdz852/wgbs/wg-blimp/fastq/rptmsk-GRCm39.csv.gz
repeat_masker_links:
  ../../../../../../work/sdz852/wgbs/wg-blimp/fastq/rptmsk-GRCm39.csv.gz: https://uni-muenster.sciebo.de/s/tFPOT7weAc5eGLG/download
samples:
- ES_L001_R1
- ES_L001_R2
- ES_L001_R3
- TF_L001_R1
- TF_L001_R2
- TF_L001_R3
target_files:
- dmr/annotated-dmrs.csv
- qc/multiqc_report.html
- qc/methylation_metrics.csv
- segmentation/umr-lmr-all.csv
temp_dir: /work/sdz852/wgbs/tmp/
transcript_start_site_file: ../../../../../../work/sdz852/wgbs/wg-blimp/fastq/tss-GRCm38.csv.gz
